### ISSUE TITLE
clientsInRoom is undefined

### ISSUE THREAD

**Issue by nurbakhyt** [webtutsplus/videoChat-WebFrontend#1]
Hi! I got the error:

https://github.com/webtutsplus/videoChat-WebFrontend/blob/280b79b59abb31ffcb40fd09cc5874c6d22a72f8/index.js#L47

```events.js:292
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Socket.<anonymous> (.../webRTC-tut/index.js:47:45)
    at Socket.emit (events.js:315:20)
```

**Comment by shivamag00** [comment]
Hi @nurbakhyt, please let me know the version of Socket.IO as mentioned in your /package.json file.

**Comment by nurbakhyt** [comment]
> Hi @nurbakhyt, please let me know the version of Socket.IO as mentioned in your /package.json file.

`"socket.io": "~1.2.1"`

**Comment by shivamag00** [comment]
@nurbakhyt  replace the above line with this - `"socket.io": "^1.2.0"` and 

* Delete `node_modules/` directory
* Delete `package-lock.json`
* Execute `npm install` again

This should surely solve your issue. Do let me know

**Comment by nurbakhyt** [comment]
thanx, actually installed `1.7.4` in `package-lock.json`:

```
"socket.io": {
      "version": "1.7.4",
      "resolved": "https://registry.npmjs.org/socket.io/-/socket.io-1.7.4.tgz",
```

**Comment by vortex-17** [comment]
Got the same error.  I tried this and it worked.

`
var clientsInRoom = io.sockets.adapter.rooms[room];
var numClients = clientsInRoom!=undefined ? Object.keys(io.sockets.adapter.rooms[room]).length:0;
`
